// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Models;

public partial class Fine : IEquatable<Fine>
{
    public int Fineid { get; set; }

    public int Recordid { get; set; }

    public int Userid { get; set; }

    public decimal Amount { get; set; }

    public string Status { get; set; }

    public DateTime? Createtime { get; set; }

    public DateTime? Updatetime { get; set; }

    public virtual Borrowrecord Record { get; set; }

    public virtual User User { get; set; }

    public override bool Equals(object obj)
    {
        return Equals(obj as Fine);
    }

    public bool Equals(Fine other)
    {
        return other is not null &&
               Fineid == other.Fineid &&
               Recordid == other.Recordid &&
               Userid == other.Userid &&
               Amount == other.Amount &&
               Status == other.Status &&
               Createtime == other.Createtime &&
               Updatetime == other.Updatetime &&
               EqualityComparer<Borrowrecord>.Default.Equals(Record, other.Record) &&
               EqualityComparer<User>.Default.Equals(User, other.User);
    }

    public override int GetHashCode()
    {
        HashCode hash = new HashCode();
        hash.Add(Fineid);
        hash.Add(Recordid);
        hash.Add(Userid);
        hash.Add(Amount);
        hash.Add(Status);
        hash.Add(Createtime);
        hash.Add(Updatetime);
        hash.Add(Record);
        hash.Add(User);
        return hash.ToHashCode();
    }

    public static bool operator ==(Fine left, Fine right)
    {
        return EqualityComparer<Fine>.Default.Equals(left, right);
    }

    public static bool operator !=(Fine left, Fine right)
    {
        return !(left == right);
    }
}